services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ../data/postgres:/var/lib/postgresql/data

    networks:
      - enterprise-network


  gitea:
    image: gitea/gitea:1.24
    container_name: gitea
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - postgres

    ports:
      - "3000:3000"
      - "2222:22"

    volumes:
      - ../data/gitea:/data

    networks:
      - enterprise-network


  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped

    ports:
      - "9000:9000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../data/portainer:/data

    networks:
      - enterprise-network


  keycloak:
    image: quay.io/keycloak/keycloak:26.3

    container_name: keycloak

    restart: unless-stopped

    command: start-dev

    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ChangeMeNow!

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminadminadmin

    ports:
      - "8080:8080"

    depends_on:
      - postgres

    networks:
      - enterprise-network

networks:
  enterprise-network:
    external: true
